-- ============================================================
-- jshERP PostgreSQL 初始化脚本
-- 从 MySQL jsh_erp.sql 转换而来
-- 目标: PostgreSQL 15+
-- 执行方式（避免 Windows PowerShell 管道把中文转成问号）:
-- docker cp jshERP-boot/docs/jsh_erp_pg.sql jsherp-postgres:/tmp/jsh_erp_pg.sql
-- docker exec jsherp-postgres psql -U postgres -d jsh_erp -f /tmp/jsh_erp_pg.sql
-- ============================================================

-- 创建数据库（在 psql 中执行）
-- CREATE DATABASE jsh_erp WITH ENCODING 'UTF8';

SET client_encoding = 'UTF8';

-- ============================================================
-- 1. jsh_account - 账户信息
-- ============================================================
DROP TABLE IF EXISTS jsh_account CASCADE;
CREATE TABLE jsh_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    serial_no VARCHAR(50),
    initial_amount DECIMAL(24,6),
    current_amount DECIMAL(24,6),
    remark VARCHAR(100),
    enabled BOOLEAN,
    sort VARCHAR(10),
    is_default BOOLEAN,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_account_tenant_id ON jsh_account(tenant_id);
COMMENT ON TABLE jsh_account IS '账户信息';
COMMENT ON COLUMN jsh_account.id IS '主键';
COMMENT ON COLUMN jsh_account.name IS '名称';
COMMENT ON COLUMN jsh_account.serial_no IS '编号';
COMMENT ON COLUMN jsh_account.initial_amount IS '期初金额';
COMMENT ON COLUMN jsh_account.current_amount IS '当前余额';
COMMENT ON COLUMN jsh_account.remark IS '备注';
COMMENT ON COLUMN jsh_account.enabled IS '启用';
COMMENT ON COLUMN jsh_account.sort IS '排序';
COMMENT ON COLUMN jsh_account.is_default IS '是否默认';
COMMENT ON COLUMN jsh_account.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_account.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_account_id_seq', 1);

-- ============================================================
-- 2. jsh_account_head - 财务主表
-- ============================================================
DROP TABLE IF EXISTS jsh_account_head CASCADE;
CREATE TABLE jsh_account_head (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),
    organ_id BIGINT,
    hands_person_id BIGINT,
    creator BIGINT,
    change_amount DECIMAL(24,6),
    discount_money DECIMAL(24,6),
    total_price DECIMAL(24,6),
    account_id BIGINT,
    bill_no VARCHAR(50),
    bill_time TIMESTAMP,
    remark VARCHAR(1000),
    file_name VARCHAR(500),
    status VARCHAR(1),
    source VARCHAR(1) DEFAULT '0',
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_account_head_organ_id ON jsh_account_head(organ_id);
CREATE INDEX idx_account_head_account_id ON jsh_account_head(account_id);
CREATE INDEX idx_account_head_hands_person_id ON jsh_account_head(hands_person_id);
CREATE INDEX idx_account_head_bill_no ON jsh_account_head(bill_no);
CREATE INDEX idx_account_head_tenant_id ON jsh_account_head(tenant_id);
CREATE UNIQUE INDEX uk_account_head_tenant_bill_no_active
ON jsh_account_head(COALESCE(tenant_id, 0), bill_no)
WHERE COALESCE(delete_flag, '0') != '1' AND bill_no IS NOT NULL;
COMMENT ON TABLE jsh_account_head IS '财务主表';
COMMENT ON COLUMN jsh_account_head.id IS '主键';
COMMENT ON COLUMN jsh_account_head.type IS '类型(支出/收入/收款/付款/转账)';
COMMENT ON COLUMN jsh_account_head.organ_id IS '单位Id(收款/付款单位)';
COMMENT ON COLUMN jsh_account_head.hands_person_id IS '经手人id';
COMMENT ON COLUMN jsh_account_head.creator IS '操作员';
COMMENT ON COLUMN jsh_account_head.change_amount IS '变动金额(优惠/收款/付款/实付)';
COMMENT ON COLUMN jsh_account_head.discount_money IS '优惠金额';
COMMENT ON COLUMN jsh_account_head.total_price IS '合计金额';
COMMENT ON COLUMN jsh_account_head.account_id IS '账户(收款/付款)';
COMMENT ON COLUMN jsh_account_head.bill_no IS '单据编号';
COMMENT ON COLUMN jsh_account_head.bill_time IS '单据日期';
COMMENT ON COLUMN jsh_account_head.remark IS '备注';
COMMENT ON COLUMN jsh_account_head.file_name IS '附件名称';
COMMENT ON COLUMN jsh_account_head.status IS '状态，0未审核、1已审核、9审核中';
COMMENT ON COLUMN jsh_account_head.source IS '单据来源，0-pc，1-手机';
COMMENT ON COLUMN jsh_account_head.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_account_head.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_account_head_id_seq', 1);

-- ============================================================
-- 3. jsh_account_item - 财务子表
-- ============================================================
DROP TABLE IF EXISTS jsh_account_item CASCADE;
CREATE TABLE jsh_account_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    header_id BIGINT NOT NULL,
    account_id BIGINT,
    in_out_item_id BIGINT,
    bill_id BIGINT,
    need_debt DECIMAL(24,6),
    finish_debt DECIMAL(24,6),
    each_amount DECIMAL(24,6),
    remark VARCHAR(500),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_account_item_account_id ON jsh_account_item(account_id);
CREATE INDEX idx_account_item_header_id ON jsh_account_item(header_id);
CREATE INDEX idx_account_item_in_out_item_id ON jsh_account_item(in_out_item_id);
CREATE INDEX idx_account_item_bill_id ON jsh_account_item(bill_id);
CREATE INDEX idx_account_item_tenant_id ON jsh_account_item(tenant_id);
COMMENT ON TABLE jsh_account_item IS '财务子表';
COMMENT ON COLUMN jsh_account_item.id IS '主键';
COMMENT ON COLUMN jsh_account_item.header_id IS '表头Id';
COMMENT ON COLUMN jsh_account_item.account_id IS '账户Id';
COMMENT ON COLUMN jsh_account_item.in_out_item_id IS '收支项目Id';
COMMENT ON COLUMN jsh_account_item.bill_id IS '单据id';
COMMENT ON COLUMN jsh_account_item.need_debt IS '应收欠款';
COMMENT ON COLUMN jsh_account_item.finish_debt IS '已收欠款';
COMMENT ON COLUMN jsh_account_item.each_amount IS '单项金额';
COMMENT ON COLUMN jsh_account_item.remark IS '单据备注';
COMMENT ON COLUMN jsh_account_item.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_account_item.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_account_item_id_seq', 1);

-- ============================================================
-- 4. jsh_depot - 仓库表
-- ============================================================
DROP TABLE IF EXISTS jsh_depot CASCADE;
CREATE TABLE jsh_depot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    address VARCHAR(50),
    warehousing DECIMAL(24,6),
    truckage DECIMAL(24,6),
    type INT,
    sort VARCHAR(10),
    remark VARCHAR(100),
    principal BIGINT,
    enabled BOOLEAN,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0',
    is_default BOOLEAN
);
CREATE INDEX idx_depot_tenant_id ON jsh_depot(tenant_id);
COMMENT ON TABLE jsh_depot IS '仓库表';
COMMENT ON COLUMN jsh_depot.id IS '主键';
COMMENT ON COLUMN jsh_depot.name IS '仓库名称';
COMMENT ON COLUMN jsh_depot.address IS '仓库地址';
COMMENT ON COLUMN jsh_depot.warehousing IS '仓储费';
COMMENT ON COLUMN jsh_depot.truckage IS '搬运费';
COMMENT ON COLUMN jsh_depot.type IS '类型';
COMMENT ON COLUMN jsh_depot.sort IS '排序';
COMMENT ON COLUMN jsh_depot.remark IS '描述';
COMMENT ON COLUMN jsh_depot.principal IS '负责人';
COMMENT ON COLUMN jsh_depot.enabled IS '启用';
COMMENT ON COLUMN jsh_depot.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_depot.delete_flag IS '删除标记，0未删除，1删除';
COMMENT ON COLUMN jsh_depot.is_default IS '是否默认';

SELECT setval('jsh_depot_id_seq', 1);

-- ============================================================
-- 5. jsh_depot_head - 单据主表
-- ============================================================
DROP TABLE IF EXISTS jsh_depot_head CASCADE;
CREATE TABLE jsh_depot_head (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),
    sub_type VARCHAR(50),
    default_number VARCHAR(50),
    number VARCHAR(50),
    create_time TIMESTAMP,
    oper_time TIMESTAMP,
    organ_id BIGINT,
    creator BIGINT,
    account_id BIGINT,
    change_amount DECIMAL(24,6),
    back_amount DECIMAL(24,6),
    total_price DECIMAL(24,6),
    pay_type VARCHAR(50),
    bill_type VARCHAR(50),
    remark VARCHAR(1000),
    file_name VARCHAR(1000),
    sales_man VARCHAR(50),
    account_id_list VARCHAR(50),
    account_money_list VARCHAR(200),
    discount DECIMAL(24,6),
    discount_money DECIMAL(24,6),
    discount_last_money DECIMAL(24,6),
    other_money DECIMAL(24,6),
    deposit DECIMAL(24,6),
    debt DECIMAL(24,6),
    last_debt DECIMAL(24,6),
    status VARCHAR(1),
    purchase_status VARCHAR(1),
    source VARCHAR(1) DEFAULT '0',
    link_number VARCHAR(50),
    link_apply VARCHAR(50),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_depot_head_organ_id ON jsh_depot_head(organ_id);
CREATE INDEX idx_depot_head_account_id ON jsh_depot_head(account_id);
CREATE INDEX idx_depot_head_number ON jsh_depot_head(number);
CREATE INDEX idx_depot_head_link_number ON jsh_depot_head(link_number);
CREATE INDEX idx_depot_head_creator ON jsh_depot_head(creator);
CREATE INDEX idx_depot_head_tenant_id ON jsh_depot_head(tenant_id);
COMMENT ON TABLE jsh_depot_head IS '单据主表';
COMMENT ON COLUMN jsh_depot_head.id IS '主键';
COMMENT ON COLUMN jsh_depot_head.type IS '类型(出库/入库)';
COMMENT ON COLUMN jsh_depot_head.sub_type IS '出入库分类';
COMMENT ON COLUMN jsh_depot_head.default_number IS '初始票据号';
COMMENT ON COLUMN jsh_depot_head.number IS '票据号';
COMMENT ON COLUMN jsh_depot_head.create_time IS '创建时间';
COMMENT ON COLUMN jsh_depot_head.oper_time IS '出入库时间';
COMMENT ON COLUMN jsh_depot_head.organ_id IS '供应商id';
COMMENT ON COLUMN jsh_depot_head.creator IS '操作员';
COMMENT ON COLUMN jsh_depot_head.account_id IS '账户id';
COMMENT ON COLUMN jsh_depot_head.change_amount IS '变动金额(收款/付款)';
COMMENT ON COLUMN jsh_depot_head.back_amount IS '找零金额';
COMMENT ON COLUMN jsh_depot_head.total_price IS '合计金额';
COMMENT ON COLUMN jsh_depot_head.pay_type IS '付款类型(现金、记账等)';
COMMENT ON COLUMN jsh_depot_head.bill_type IS '单据类型';
COMMENT ON COLUMN jsh_depot_head.remark IS '备注';
COMMENT ON COLUMN jsh_depot_head.file_name IS '附件名称';
COMMENT ON COLUMN jsh_depot_head.sales_man IS '销售员（可以多个）';
COMMENT ON COLUMN jsh_depot_head.account_id_list IS '多账户ID列表';
COMMENT ON COLUMN jsh_depot_head.account_money_list IS '多账户金额列表';
COMMENT ON COLUMN jsh_depot_head.discount IS '优惠率';
COMMENT ON COLUMN jsh_depot_head.discount_money IS '优惠金额';
COMMENT ON COLUMN jsh_depot_head.discount_last_money IS '优惠后金额';
COMMENT ON COLUMN jsh_depot_head.other_money IS '销售或采购费用合计';
COMMENT ON COLUMN jsh_depot_head.deposit IS '订金';
COMMENT ON COLUMN jsh_depot_head.debt IS '本次欠款';
COMMENT ON COLUMN jsh_depot_head.last_debt IS '最终欠款';
COMMENT ON COLUMN jsh_depot_head.status IS '状态，0未审核、1已审核、2完成采购|销售、3部分采购|销售、9审核中';
COMMENT ON COLUMN jsh_depot_head.purchase_status IS '采购状态，0未采购、2完成采购、3部分采购';
COMMENT ON COLUMN jsh_depot_head.source IS '单据来源，0-pc，1-手机';
COMMENT ON COLUMN jsh_depot_head.link_number IS '关联订单号';
COMMENT ON COLUMN jsh_depot_head.link_apply IS '关联请购单';
COMMENT ON COLUMN jsh_depot_head.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_depot_head.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_depot_head_id_seq', 1);

-- ============================================================
-- 6. jsh_depot_item - 单据子表
-- ============================================================
DROP TABLE IF EXISTS jsh_depot_item CASCADE;
CREATE TABLE jsh_depot_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    header_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    material_extend_id BIGINT,
    material_unit VARCHAR(20),
    sku VARCHAR(50),
    oper_number DECIMAL(24,6),
    basic_number DECIMAL(24,6),
    unit_price DECIMAL(24,6),
    purchase_unit_price DECIMAL(24,6),
    tax_unit_price DECIMAL(24,6),
    all_price DECIMAL(24,6),
    remark VARCHAR(500),
    depot_id BIGINT,
    another_depot_id BIGINT,
    tax_rate DECIMAL(24,6),
    tax_money DECIMAL(24,6),
    tax_last_money DECIMAL(24,6),
    material_type VARCHAR(20),
    sn_list VARCHAR(2000),
    batch_number VARCHAR(100),
    expiration_date TIMESTAMP,
    link_id BIGINT,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_depot_item_material_id ON jsh_depot_item(material_id);
CREATE INDEX idx_depot_item_header_id ON jsh_depot_item(header_id);
CREATE INDEX idx_depot_item_depot_id ON jsh_depot_item(depot_id);
CREATE INDEX idx_depot_item_another_depot_id ON jsh_depot_item(another_depot_id);
CREATE INDEX idx_depot_item_material_extend_id ON jsh_depot_item(material_extend_id);
CREATE INDEX idx_depot_item_tenant_id ON jsh_depot_item(tenant_id);
COMMENT ON TABLE jsh_depot_item IS '单据子表';
COMMENT ON COLUMN jsh_depot_item.id IS '主键';
COMMENT ON COLUMN jsh_depot_item.header_id IS '表头Id';
COMMENT ON COLUMN jsh_depot_item.material_id IS '商品Id';
COMMENT ON COLUMN jsh_depot_item.material_extend_id IS '商品扩展id';
COMMENT ON COLUMN jsh_depot_item.material_unit IS '商品单位';
COMMENT ON COLUMN jsh_depot_item.sku IS '多属性';
COMMENT ON COLUMN jsh_depot_item.oper_number IS '数量';
COMMENT ON COLUMN jsh_depot_item.basic_number IS '基础数量，如kg、瓶';
COMMENT ON COLUMN jsh_depot_item.unit_price IS '单价';
COMMENT ON COLUMN jsh_depot_item.purchase_unit_price IS '采购单价';
COMMENT ON COLUMN jsh_depot_item.tax_unit_price IS '含税单价';
COMMENT ON COLUMN jsh_depot_item.all_price IS '金额';
COMMENT ON COLUMN jsh_depot_item.remark IS '备注';
COMMENT ON COLUMN jsh_depot_item.depot_id IS '仓库ID';
COMMENT ON COLUMN jsh_depot_item.another_depot_id IS '调拨时，对方仓库Id';
COMMENT ON COLUMN jsh_depot_item.tax_rate IS '税率';
COMMENT ON COLUMN jsh_depot_item.tax_money IS '税额';
COMMENT ON COLUMN jsh_depot_item.tax_last_money IS '价税合计';
COMMENT ON COLUMN jsh_depot_item.material_type IS '商品类型';
COMMENT ON COLUMN jsh_depot_item.sn_list IS '序列号列表';
COMMENT ON COLUMN jsh_depot_item.batch_number IS '批号';
COMMENT ON COLUMN jsh_depot_item.expiration_date IS '有效日期';
COMMENT ON COLUMN jsh_depot_item.link_id IS '关联明细id';
COMMENT ON COLUMN jsh_depot_item.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_depot_item.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_depot_item_id_seq', 1);

-- ============================================================
-- 7. jsh_function - 功能模块表
-- ============================================================
DROP TABLE IF EXISTS jsh_function CASCADE;
CREATE TABLE jsh_function (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(50),
    name VARCHAR(50),
    parent_number VARCHAR(50),
    url VARCHAR(100),
    component VARCHAR(100),
    state BOOLEAN,
    sort VARCHAR(50),
    enabled BOOLEAN,
    type VARCHAR(50),
    push_btn VARCHAR(50),
    icon VARCHAR(50),
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE UNIQUE INDEX idx_function_url ON jsh_function(url);
COMMENT ON TABLE jsh_function IS '功能模块表';
COMMENT ON COLUMN jsh_function.id IS '主键';
COMMENT ON COLUMN jsh_function.number IS '编号';
COMMENT ON COLUMN jsh_function.name IS '名称';
COMMENT ON COLUMN jsh_function.parent_number IS '上级编号';
COMMENT ON COLUMN jsh_function.url IS '链接';
COMMENT ON COLUMN jsh_function.component IS '组件';
COMMENT ON COLUMN jsh_function.state IS '收缩';
COMMENT ON COLUMN jsh_function.sort IS '排序';
COMMENT ON COLUMN jsh_function.enabled IS '启用';
COMMENT ON COLUMN jsh_function.type IS '类型';
COMMENT ON COLUMN jsh_function.push_btn IS '功能按钮';
COMMENT ON COLUMN jsh_function.icon IS '图标';
COMMENT ON COLUMN jsh_function.delete_flag IS '删除标记，0未删除，1删除';

-- ============================================
INSERT INTO jsh_function (id, number, name, parent_number, url, component, state, sort, enabled, type, push_btn, icon, delete_flag) VALUES
(1, '0001', '系统管理', '0', '/system', '/layouts/TabLayout', TRUE, '0910', TRUE, '电脑版', '', 'setting', '0'),
(13, '000102', '角色管理', '0001', '/system/role', '/system/RoleList', FALSE, '0130', TRUE, '电脑版', '1', 'profile', '0'),
(14, '000103', '用户管理', '0001', '/system/user', '/system/UserList', FALSE, '0140', TRUE, '电脑版', '1', 'profile', '0'),
(15, '000104', '日志管理', '0001', '/system/log', '/system/LogList', FALSE, '0160', TRUE, '电脑版', '', 'profile', '0'),
(16, '000105', '菜单管理', '0001', '/system/function', '/system/FunctionList', FALSE, '0166', TRUE, '电脑版', '1', 'profile', '0'),
(18, '000109', '租户管理', '0001', '/system/tenant', '/system/TenantList', FALSE, '0167', TRUE, '电脑版', '1', 'profile', '0'),
(21, '0101', '商品管理', '0', '/material', '/layouts/TabLayout', FALSE, '0620', TRUE, '电脑版', NULL, 'shopping', '0'),
(22, '010101', '商品类别', '0101', '/material/material_category', '/material/MaterialCategoryList', FALSE, '0230', TRUE, '电脑版', '1', 'profile', '0'),
(23, '010102', '商品信息', '0101', '/material/material', '/material/MaterialList', FALSE, '0240', TRUE, '电脑版', '1,3', 'profile', '0'),
(24, '0102', '基础资料', '0', '/systemA', '/layouts/TabLayout', FALSE, '0750', TRUE, '电脑版', NULL, 'appstore', '0'),
(25, '01020101', '供应商信息', '0102', '/system/vendor', '/system/VendorList', FALSE, '0260', TRUE, '电脑版', '1,3', 'profile', '0'),
(26, '010202', '仓库信息', '0102', '/system/depot', '/system/DepotList', FALSE, '0270', TRUE, '电脑版', '1', 'profile', '0'),
(31, '010206', '经手人管理', '0102', '/system/person', '/system/PersonList', FALSE, '0284', TRUE, '电脑版', '1', 'profile', '0'),
(32, '0502', '采购管理', '0', '/bill', '/layouts/TabLayout', FALSE, '0330', TRUE, '电脑版', '', 'retweet', '0'),
(33, '050201', '采购入库', '0502', '/bill/purchase_in', '/bill/PurchaseInList', FALSE, '0340', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(38, '0603', '销售管理', '0', '/billB', '/layouts/TabLayout', FALSE, '0390', TRUE, '电脑版', '', 'shopping-cart', '0'),
(40, '080107', '调拨出库', '0801', '/bill/allocation_out', '/bill/AllocationOutList', FALSE, '0807', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(41, '060303', '销售出库', '0603', '/bill/sale_out', '/bill/SaleOutList', FALSE, '0394', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(44, '0704', '财务管理', '0', '/financial', '/layouts/TabLayout', FALSE, '0450', TRUE, '电脑版', '', 'money-collect', '0'),
(59, '030101', '进销存统计', '0301', '/report/in_out_stock_report', '/report/InOutStockReport', FALSE, '0658', TRUE, '电脑版', '', 'profile', '0'),
(194, '010204', '收支项目', '0102', '/system/in_out_item', '/system/InOutItemList', FALSE, '0282', TRUE, '电脑版', '1', 'profile', '0'),
(195, '010205', '结算账户', '0102', '/system/account', '/system/AccountList', FALSE, '0283', TRUE, '电脑版', '1', 'profile', '0'),
(197, '070402', '收入单', '0704', '/financial/item_in', '/financial/ItemInList', FALSE, '0465', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(198, '0301', '报表查询', '0', '/report', '/layouts/TabLayout', FALSE, '0570', TRUE, '电脑版', NULL, 'pie-chart', '0'),
(199, '050204', '采购退货', '0502', '/bill/purchase_back', '/bill/PurchaseBackList', FALSE, '0345', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(200, '060305', '销售退货', '0603', '/bill/sale_back', '/bill/SaleBackList', FALSE, '0396', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(201, '080103', '其它入库', '0801', '/bill/other_in', '/bill/OtherInList', FALSE, '0803', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(202, '080105', '其它出库', '0801', '/bill/other_out', '/bill/OtherOutList', FALSE, '0805', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(203, '070403', '支出单', '0704', '/financial/item_out', '/financial/ItemOutList', FALSE, '0470', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(204, '070404', '收款单', '0704', '/financial/money_in', '/financial/MoneyInList', FALSE, '0475', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(205, '070405', '付款单', '0704', '/financial/money_out', '/financial/MoneyOutList', FALSE, '0480', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(206, '070406', '转账单', '0704', '/financial/giro', '/financial/GiroList', FALSE, '0490', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(207, '030102', '账户统计', '0301', '/report/account_report', '/report/AccountReport', FALSE, '0610', TRUE, '电脑版', '', 'profile', '0'),
(208, '030103', '采购统计', '0301', '/report/buy_in_report', '/report/BuyInReport', FALSE, '0620', TRUE, '电脑版', '', 'profile', '0'),
(209, '030104', '销售统计', '0301', '/report/sale_out_report', '/report/SaleOutReport', FALSE, '0630', TRUE, '电脑版', '', 'profile', '0'),
(210, '040102', '零售出库', '0401', '/bill/retail_out', '/bill/RetailOutList', FALSE, '0405', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(211, '040104', '零售退货', '0401', '/bill/retail_back', '/bill/RetailBackList', FALSE, '0407', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(212, '070407', '收预付款', '0704', '/financial/advance_in', '/financial/AdvanceInList', FALSE, '0495', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(217, '01020102', '客户信息', '0102', '/system/customer', '/system/CustomerList', FALSE, '0262', TRUE, '电脑版', '1,3', 'profile', '0'),
(218, '01020103', '会员信息', '0102', '/system/member', '/system/MemberList', FALSE, '0263', TRUE, '电脑版', '1,3', 'profile', '0'),
(220, '010103', '多单位', '0101', '/system/unit', '/system/UnitList', FALSE, '0245', TRUE, '电脑版', '1', 'profile', '0'),
(225, '0401', '零售管理', '0', '/billC', '/layouts/TabLayout', FALSE, '0101', TRUE, '电脑版', '', 'gift', '0'),
(226, '030106', '入库明细', '0301', '/report/in_detail', '/report/InDetail', FALSE, '0640', TRUE, '电脑版', '', 'profile', '0'),
(227, '030107', '出库明细', '0301', '/report/out_detail', '/report/OutDetail', FALSE, '0645', TRUE, '电脑版', '', 'profile', '0'),
(228, '030108', '入库汇总', '0301', '/report/in_material_count', '/report/InMaterialCount', FALSE, '0650', TRUE, '电脑版', '', 'profile', '0'),
(229, '030109', '出库汇总', '0301', '/report/out_material_count', '/report/OutMaterialCount', FALSE, '0655', TRUE, '电脑版', '', 'profile', '0'),
(232, '080109', '组装单', '0801', '/bill/assemble', '/bill/AssembleList', FALSE, '0809', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(233, '080111', '拆卸单', '0801', '/bill/disassemble', '/bill/DisassembleList', FALSE, '0811', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(234, '000105', '系统配置', '0001', '/system/system_config', '/system/SystemConfigList', FALSE, '0164', TRUE, '电脑版', '1', 'profile', '0'),
(235, '030110', '客户对账', '0301', '/report/customer_account', '/report/CustomerAccount', FALSE, '0660', TRUE, '电脑版', '', 'profile', '0'),
(236, '000106', '商品属性', '0001', '/material/material_property', '/material/MaterialPropertyList', FALSE, '0163', TRUE, '电脑版', '1', 'profile', '0'),
(237, '030111', '供应商对账', '0301', '/report/vendor_account', '/report/VendorAccount', FALSE, '0665', TRUE, '电脑版', '', 'profile', '0'),
(239, '0801', '仓库管理', '0', '/billD', '/layouts/TabLayout', FALSE, '0420', TRUE, '电脑版', '', 'hdd', '0'),
(241, '050202', '采购订单', '0502', '/bill/purchase_order', '/bill/PurchaseOrderList', FALSE, '0335', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(242, '060301', '销售订单', '0603', '/bill/sale_order', '/bill/SaleOrderList', FALSE, '0392', TRUE, '电脑版', '1,2,3,7', 'profile', '0'),
(243, '000108', '部门管理', '0001', '/system/organization', '/system/OrganizationList', TRUE, '0150', TRUE, '电脑版', '1', 'profile', '0'),
(244, '030112', '库存预警', '0301', '/report/stock_warning_report', '/report/StockWarningReport', FALSE, '0670', TRUE, '电脑版', '', 'profile', '0'),
(245, '000107', '插件管理', '0001', '/system/plugin', '/system/PluginList', FALSE, '0170', TRUE, '电脑版', '1', 'profile', '0'),
(246, '030113', '商品库存', '0301', '/report/material_stock', '/report/MaterialStock', FALSE, '0605', TRUE, '电脑版', '', 'profile', '0'),
(247, '010105', '多属性', '0101', '/material/material_attribute', '/material/MaterialAttributeList', FALSE, '0250', TRUE, '电脑版', '1', 'profile', '0'),
(248, '030150', '调拨明细', '0301', '/report/allocation_detail', '/report/AllocationDetail', FALSE, '0646', TRUE, '电脑版', '', 'profile', '0'),
(258, '000112', '平台配置', '0001', '/system/platform_config', '/system/PlatformConfigList', FALSE, '0175', TRUE, '电脑版', '', 'profile', '0'),
(259, '030105', '零售统计', '0301', '/report/retail_out_report', '/report/RetailOutReport', FALSE, '0615', TRUE, '电脑版', '', 'profile', '0'),
(260, '000113', '字典管理', '0001', '/system/dict', '/system/DictList', FALSE, '0172', TRUE, '电脑版', '', 'profile', '0'),
(261, '050203', '请购单', '0502', '/bill/purchase_apply', '/bill/PurchaseApplyList', FALSE, '0330', TRUE, '电脑版', '1,2,3,7', 'profile', '0')
ON CONFLICT (id) DO NOTHING;

SELECT setval('jsh_function_id_seq', COALESCE((SELECT MAX(id) FROM jsh_function), 1));

-- ============================================================
-- 8. jsh_in_out_item - 收支项目
-- ============================================================
DROP TABLE IF EXISTS jsh_in_out_item CASCADE;
CREATE TABLE jsh_in_out_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    type VARCHAR(20),
    remark VARCHAR(100),
    enabled BOOLEAN,
    sort VARCHAR(10),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_in_out_item_tenant_id ON jsh_in_out_item(tenant_id);
COMMENT ON TABLE jsh_in_out_item IS '收支项目';
COMMENT ON COLUMN jsh_in_out_item.id IS '主键';
COMMENT ON COLUMN jsh_in_out_item.name IS '名称';
COMMENT ON COLUMN jsh_in_out_item.type IS '类型';
COMMENT ON COLUMN jsh_in_out_item.remark IS '备注';
COMMENT ON COLUMN jsh_in_out_item.enabled IS '启用';
COMMENT ON COLUMN jsh_in_out_item.sort IS '排序';
COMMENT ON COLUMN jsh_in_out_item.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_in_out_item.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_in_out_item_id_seq', 1);

-- ============================================================
-- 9. jsh_log - 操作日志
-- ============================================================
DROP TABLE IF EXISTS jsh_log CASCADE;
CREATE TABLE jsh_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    operation VARCHAR(500),
    client_ip VARCHAR(200),
    create_time TIMESTAMP,
    status SMALLINT,
    content VARCHAR(5000),
    tenant_id BIGINT
);
CREATE INDEX idx_log_user_id ON jsh_log(user_id);
CREATE INDEX idx_log_create_time ON jsh_log(create_time);
CREATE INDEX idx_log_tenant_id ON jsh_log(tenant_id);
COMMENT ON TABLE jsh_log IS '操作日志';
COMMENT ON COLUMN jsh_log.id IS '主键';
COMMENT ON COLUMN jsh_log.user_id IS '用户id';
COMMENT ON COLUMN jsh_log.operation IS '操作模块名称';
COMMENT ON COLUMN jsh_log.client_ip IS '客户端IP';
COMMENT ON COLUMN jsh_log.create_time IS '创建时间';
COMMENT ON COLUMN jsh_log.status IS '操作状态 0==成功，1==失败';
COMMENT ON COLUMN jsh_log.content IS '详情';
COMMENT ON COLUMN jsh_log.tenant_id IS '租户id';

-- ============================================================
-- 10. jsh_material - 产品表
-- ============================================================
DROP TABLE IF EXISTS jsh_material CASCADE;
CREATE TABLE jsh_material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    name VARCHAR(100),
    mfrs VARCHAR(50),
    model VARCHAR(100),
    standard VARCHAR(100),
    brand VARCHAR(100),
    mnemonic VARCHAR(100),
    color VARCHAR(50),
    unit VARCHAR(50),
    remark VARCHAR(500),
    img_name VARCHAR(1000),
    unit_id BIGINT,
    expiry_num INT,
    weight DECIMAL(24,6),
    enabled BOOLEAN,
    other_field1 VARCHAR(500),
    other_field2 VARCHAR(500),
    other_field3 VARCHAR(500),
    enable_serial_number VARCHAR(1) DEFAULT '0',
    enable_batch_number VARCHAR(1) DEFAULT '0',
    position VARCHAR(100),
    attribute VARCHAR(1000),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_material_category_id ON jsh_material(category_id);
CREATE INDEX idx_material_unit_id ON jsh_material(unit_id);
CREATE INDEX idx_material_tenant_id ON jsh_material(tenant_id);
COMMENT ON TABLE jsh_material IS '产品表';
COMMENT ON COLUMN jsh_material.id IS '主键';
COMMENT ON COLUMN jsh_material.category_id IS '产品类型id';
COMMENT ON COLUMN jsh_material.name IS '名称';
COMMENT ON COLUMN jsh_material.mfrs IS '制造商';
COMMENT ON COLUMN jsh_material.model IS '型号';
COMMENT ON COLUMN jsh_material.standard IS '规格';
COMMENT ON COLUMN jsh_material.brand IS '品牌';
COMMENT ON COLUMN jsh_material.mnemonic IS '助记码';
COMMENT ON COLUMN jsh_material.color IS '颜色';
COMMENT ON COLUMN jsh_material.unit IS '单位-单个';
COMMENT ON COLUMN jsh_material.remark IS '备注';
COMMENT ON COLUMN jsh_material.img_name IS '图片名称';
COMMENT ON COLUMN jsh_material.unit_id IS '单位Id';
COMMENT ON COLUMN jsh_material.expiry_num IS '保质期天数';
COMMENT ON COLUMN jsh_material.weight IS '基础重量(kg)';
COMMENT ON COLUMN jsh_material.enabled IS '启用 0-禁用  1-启用';
COMMENT ON COLUMN jsh_material.other_field1 IS '自定义1';
COMMENT ON COLUMN jsh_material.other_field2 IS '自定义2';
COMMENT ON COLUMN jsh_material.other_field3 IS '自定义3';
COMMENT ON COLUMN jsh_material.enable_serial_number IS '是否开启序列号，0否，1是';
COMMENT ON COLUMN jsh_material.enable_batch_number IS '是否开启批号，0否，1是';
COMMENT ON COLUMN jsh_material.position IS '仓位货架';
COMMENT ON COLUMN jsh_material.attribute IS '多属性信息';
COMMENT ON COLUMN jsh_material.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_material_id_seq', 1);

-- ============================================================
-- 11. jsh_material_attribute - 产品属性表
-- ============================================================
DROP TABLE IF EXISTS jsh_material_attribute CASCADE;
CREATE TABLE jsh_material_attribute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_name VARCHAR(50),
    attribute_value VARCHAR(500),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_material_attribute_tenant_id ON jsh_material_attribute(tenant_id);
COMMENT ON TABLE jsh_material_attribute IS '产品属性表';
COMMENT ON COLUMN jsh_material_attribute.id IS '主键';
COMMENT ON COLUMN jsh_material_attribute.attribute_name IS '属性名';
COMMENT ON COLUMN jsh_material_attribute.attribute_value IS '属性值';
COMMENT ON COLUMN jsh_material_attribute.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material_attribute.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_material_attribute_id_seq', 1);

-- ============================================================
-- 12. jsh_material_category - 产品类型表
-- ============================================================
DROP TABLE IF EXISTS jsh_material_category CASCADE;
CREATE TABLE jsh_material_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    category_level SMALLINT,
    parent_id BIGINT,
    sort VARCHAR(10),
    serial_no VARCHAR(100),
    remark VARCHAR(1024),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_material_category_parent_id ON jsh_material_category(parent_id);
CREATE INDEX idx_material_category_tenant_id ON jsh_material_category(tenant_id);
COMMENT ON TABLE jsh_material_category IS '产品类型表';
COMMENT ON COLUMN jsh_material_category.id IS '主键';
COMMENT ON COLUMN jsh_material_category.name IS '名称';
COMMENT ON COLUMN jsh_material_category.category_level IS '等级';
COMMENT ON COLUMN jsh_material_category.parent_id IS '上级id';
COMMENT ON COLUMN jsh_material_category.sort IS '显示顺序';
COMMENT ON COLUMN jsh_material_category.serial_no IS '编号';
COMMENT ON COLUMN jsh_material_category.remark IS '备注';
COMMENT ON COLUMN jsh_material_category.create_time IS '创建时间';
COMMENT ON COLUMN jsh_material_category.update_time IS '更新时间';
COMMENT ON COLUMN jsh_material_category.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material_category.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_material_category_id_seq', 1);

-- ============================================================
-- 13. jsh_material_current_stock - 产品当前库存
-- ============================================================
DROP TABLE IF EXISTS jsh_material_current_stock CASCADE;
CREATE TABLE jsh_material_current_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT,
    depot_id BIGINT,
    current_number DECIMAL(24,6),
    current_unit_price DECIMAL(24,6),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_material_current_stock_material_id ON jsh_material_current_stock(material_id);
CREATE INDEX idx_material_current_stock_depot_id ON jsh_material_current_stock(depot_id);
CREATE INDEX idx_material_current_stock_tenant_id ON jsh_material_current_stock(tenant_id);
COMMENT ON TABLE jsh_material_current_stock IS '产品当前库存';
COMMENT ON COLUMN jsh_material_current_stock.id IS '主键';
COMMENT ON COLUMN jsh_material_current_stock.material_id IS '产品id';
COMMENT ON COLUMN jsh_material_current_stock.depot_id IS '仓库id';
COMMENT ON COLUMN jsh_material_current_stock.current_number IS '当前库存数量';
COMMENT ON COLUMN jsh_material_current_stock.current_unit_price IS '当前单价';
COMMENT ON COLUMN jsh_material_current_stock.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material_current_stock.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_material_current_stock_id_seq', 1);

-- ============================================================
-- 14. jsh_material_extend - 产品价格扩展
-- ============================================================
DROP TABLE IF EXISTS jsh_material_extend CASCADE;
CREATE TABLE jsh_material_extend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT,
    bar_code VARCHAR(50),
    commodity_unit VARCHAR(50),
    sku VARCHAR(50),
    purchase_decimal DECIMAL(24,6),
    commodity_decimal DECIMAL(24,6),
    wholesale_decimal DECIMAL(24,6),
    low_decimal DECIMAL(24,6),
    default_flag VARCHAR(1) DEFAULT '1',
    create_time TIMESTAMP,
    create_serial VARCHAR(50),
    update_serial VARCHAR(50),
    update_time BIGINT,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_material_extend_material_id ON jsh_material_extend(material_id);
CREATE INDEX idx_material_extend_bar_code ON jsh_material_extend(bar_code);
CREATE INDEX idx_material_extend_tenant_id ON jsh_material_extend(tenant_id);
COMMENT ON TABLE jsh_material_extend IS '产品价格扩展';
COMMENT ON COLUMN jsh_material_extend.id IS '主键';
COMMENT ON COLUMN jsh_material_extend.material_id IS '商品id';
COMMENT ON COLUMN jsh_material_extend.bar_code IS '商品条码';
COMMENT ON COLUMN jsh_material_extend.commodity_unit IS '商品单位';
COMMENT ON COLUMN jsh_material_extend.sku IS '多属性';
COMMENT ON COLUMN jsh_material_extend.purchase_decimal IS '采购价格';
COMMENT ON COLUMN jsh_material_extend.commodity_decimal IS '零售价格';
COMMENT ON COLUMN jsh_material_extend.wholesale_decimal IS '销售价格';
COMMENT ON COLUMN jsh_material_extend.low_decimal IS '最低售价';
COMMENT ON COLUMN jsh_material_extend.default_flag IS '是否为默认单位，1是，0否';
COMMENT ON COLUMN jsh_material_extend.create_time IS '创建日期';
COMMENT ON COLUMN jsh_material_extend.create_serial IS '创建人编码';
COMMENT ON COLUMN jsh_material_extend.update_serial IS '更新人编码';
COMMENT ON COLUMN jsh_material_extend.update_time IS '更新时间戳';
COMMENT ON COLUMN jsh_material_extend.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material_extend.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_material_extend_id_seq', 1);

-- ============================================================
-- 15. jsh_material_initial_stock - 产品初始库存
-- ============================================================
DROP TABLE IF EXISTS jsh_material_initial_stock CASCADE;
CREATE TABLE jsh_material_initial_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT,
    depot_id BIGINT,
    number DECIMAL(24,6),
    low_safe_stock DECIMAL(24,6),
    high_safe_stock DECIMAL(24,6),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_material_initial_stock_material_id ON jsh_material_initial_stock(material_id);
CREATE INDEX idx_material_initial_stock_depot_id ON jsh_material_initial_stock(depot_id);
CREATE INDEX idx_material_initial_stock_tenant_id ON jsh_material_initial_stock(tenant_id);
COMMENT ON TABLE jsh_material_initial_stock IS '产品初始库存';
COMMENT ON COLUMN jsh_material_initial_stock.id IS '主键';
COMMENT ON COLUMN jsh_material_initial_stock.material_id IS '产品id';
COMMENT ON COLUMN jsh_material_initial_stock.depot_id IS '仓库id';
COMMENT ON COLUMN jsh_material_initial_stock.number IS '初始库存数量';
COMMENT ON COLUMN jsh_material_initial_stock.low_safe_stock IS '最低库存数量';
COMMENT ON COLUMN jsh_material_initial_stock.high_safe_stock IS '最高库存数量';
COMMENT ON COLUMN jsh_material_initial_stock.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material_initial_stock.delete_flag IS '删除标记，0未删除，1删除';

-- ============================================================
-- 16. jsh_material_property - 产品扩展字段表
-- ============================================================
DROP TABLE IF EXISTS jsh_material_property CASCADE;
CREATE TABLE jsh_material_property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    native_name VARCHAR(50),
    enabled BOOLEAN,
    sort VARCHAR(10),
    another_name VARCHAR(50),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
COMMENT ON TABLE jsh_material_property IS '产品扩展字段表';
COMMENT ON COLUMN jsh_material_property.id IS '主键';
COMMENT ON COLUMN jsh_material_property.native_name IS '原始名称';
COMMENT ON COLUMN jsh_material_property.enabled IS '是否启用';
COMMENT ON COLUMN jsh_material_property.sort IS '排序';
COMMENT ON COLUMN jsh_material_property.another_name IS '别名';
COMMENT ON COLUMN jsh_material_property.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_material_property.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_material_property_id_seq', 1);

-- ============================================================
-- 17. jsh_msg - 消息表
-- ============================================================
DROP TABLE IF EXISTS jsh_msg CASCADE;
CREATE TABLE jsh_msg (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msg_title VARCHAR(100),
    msg_content VARCHAR(500),
    create_time TIMESTAMP,
    type VARCHAR(20),
    user_id BIGINT,
    status VARCHAR(1),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_msg_tenant_id ON jsh_msg(tenant_id);
COMMENT ON TABLE jsh_msg IS '消息表';
COMMENT ON COLUMN jsh_msg.id IS '主键';
COMMENT ON COLUMN jsh_msg.msg_title IS '消息标题';
COMMENT ON COLUMN jsh_msg.msg_content IS '消息内容';
COMMENT ON COLUMN jsh_msg.create_time IS '创建时间';
COMMENT ON COLUMN jsh_msg.type IS '消息类型';
COMMENT ON COLUMN jsh_msg.user_id IS '接收人id';
COMMENT ON COLUMN jsh_msg.status IS '状态，1未读 2已读';
COMMENT ON COLUMN jsh_msg.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_msg.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_msg_id_seq', 1);

-- ============================================================
-- 18. jsh_orga_user_rel - 部门用户关系表
-- ============================================================
DROP TABLE IF EXISTS jsh_orga_user_rel CASCADE;
CREATE TABLE jsh_orga_user_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orga_id BIGINT,
    user_id BIGINT NOT NULL,
    user_blng_orga_dspl_seq VARCHAR(20),
    delete_flag CHAR(1) DEFAULT '0',
    create_time TIMESTAMP,
    creator BIGINT,
    update_time TIMESTAMP,
    updater BIGINT,
    tenant_id BIGINT
);
CREATE INDEX idx_orga_user_rel_orga_id ON jsh_orga_user_rel(orga_id);
CREATE INDEX idx_orga_user_rel_user_id ON jsh_orga_user_rel(user_id);
CREATE INDEX idx_orga_user_rel_creator ON jsh_orga_user_rel(creator);
CREATE INDEX idx_orga_user_rel_tenant_id ON jsh_orga_user_rel(tenant_id);
COMMENT ON TABLE jsh_orga_user_rel IS '部门用户关系表';
COMMENT ON COLUMN jsh_orga_user_rel.id IS '主键';
COMMENT ON COLUMN jsh_orga_user_rel.orga_id IS '部门id';
COMMENT ON COLUMN jsh_orga_user_rel.user_id IS '用户id';
COMMENT ON COLUMN jsh_orga_user_rel.user_blng_orga_dspl_seq IS '用户在所属部门中显示顺序';
COMMENT ON COLUMN jsh_orga_user_rel.delete_flag IS '删除标记，0未删除，1删除';
COMMENT ON COLUMN jsh_orga_user_rel.create_time IS '创建时间';
COMMENT ON COLUMN jsh_orga_user_rel.creator IS '创建人';
COMMENT ON COLUMN jsh_orga_user_rel.update_time IS '更新时间';
COMMENT ON COLUMN jsh_orga_user_rel.updater IS '更新人';
COMMENT ON COLUMN jsh_orga_user_rel.tenant_id IS '租户id';

SELECT setval('jsh_orga_user_rel_id_seq', 1);

-- ============================================================
-- 19. jsh_organization - 部门表
-- ============================================================
DROP TABLE IF EXISTS jsh_organization CASCADE;
CREATE TABLE jsh_organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_no VARCHAR(20),
    org_abr VARCHAR(20),
    parent_id BIGINT,
    sort VARCHAR(20),
    remark VARCHAR(500),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_organization_tenant_id ON jsh_organization(tenant_id);
COMMENT ON TABLE jsh_organization IS '部门表';
COMMENT ON COLUMN jsh_organization.id IS '主键';
COMMENT ON COLUMN jsh_organization.org_no IS '部门编号';
COMMENT ON COLUMN jsh_organization.org_abr IS '部门简称';
COMMENT ON COLUMN jsh_organization.parent_id IS '父部门id';
COMMENT ON COLUMN jsh_organization.sort IS '部门显示顺序';
COMMENT ON COLUMN jsh_organization.remark IS '备注';
COMMENT ON COLUMN jsh_organization.create_time IS '创建时间';
COMMENT ON COLUMN jsh_organization.update_time IS '更新时间';
COMMENT ON COLUMN jsh_organization.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_organization.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_organization_id_seq', 1);

-- ============================================================
-- 20. jsh_person - 经手人表
-- ============================================================
DROP TABLE IF EXISTS jsh_person CASCADE;
CREATE TABLE jsh_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20),
    name VARCHAR(50),
    enabled BOOLEAN,
    sort VARCHAR(10),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_person_tenant_id ON jsh_person(tenant_id);
COMMENT ON TABLE jsh_person IS '经手人表';
COMMENT ON COLUMN jsh_person.id IS '主键';
COMMENT ON COLUMN jsh_person.type IS '类型';
COMMENT ON COLUMN jsh_person.name IS '姓名';
COMMENT ON COLUMN jsh_person.enabled IS '启用';
COMMENT ON COLUMN jsh_person.sort IS '排序';
COMMENT ON COLUMN jsh_person.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_person.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_person_id_seq', 1);

-- ============================================================
-- 21. jsh_platform_config - 平台参数
-- ============================================================
DROP TABLE IF EXISTS jsh_platform_config CASCADE;
CREATE TABLE jsh_platform_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_key VARCHAR(100),
    platform_key_info VARCHAR(100),
    platform_value VARCHAR(200)
);
COMMENT ON TABLE jsh_platform_config IS '平台参数';
COMMENT ON COLUMN jsh_platform_config.id IS '主键';
COMMENT ON COLUMN jsh_platform_config.platform_key IS '关键词';
COMMENT ON COLUMN jsh_platform_config.platform_key_info IS '关键词名称';
COMMENT ON COLUMN jsh_platform_config.platform_value IS '值';

SELECT setval('jsh_platform_config_id_seq', 1);

-- ============================================================
-- 22. jsh_role - 角色表
-- ============================================================
DROP TABLE IF EXISTS jsh_role CASCADE;
CREATE TABLE jsh_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    type VARCHAR(50),
    price_limit VARCHAR(50),
    value VARCHAR(200),
    description VARCHAR(100),
    enabled BOOLEAN,
    sort VARCHAR(10),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_role_tenant_id ON jsh_role(tenant_id);
COMMENT ON TABLE jsh_role IS '角色表';
COMMENT ON COLUMN jsh_role.id IS '主键';
COMMENT ON COLUMN jsh_role.name IS '名称';
COMMENT ON COLUMN jsh_role.type IS '类型';
COMMENT ON COLUMN jsh_role.price_limit IS '价格屏蔽 1-屏蔽采购价 2-屏蔽零售价 3-屏蔽销售价';
COMMENT ON COLUMN jsh_role.value IS '值';
COMMENT ON COLUMN jsh_role.description IS '描述';
COMMENT ON COLUMN jsh_role.enabled IS '启用';
COMMENT ON COLUMN jsh_role.sort IS '排序';
COMMENT ON COLUMN jsh_role.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_role.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_role_id_seq', 1);

INSERT INTO jsh_role (id, name, type, price_limit, value, description, enabled, sort, tenant_id, delete_flag) VALUES
(4, '管理员', '全部数据', NULL, NULL, '平台运维管理员', TRUE, NULL, NULL, '0')
ON CONFLICT (id) DO UPDATE SET
name = EXCLUDED.name,
type = EXCLUDED.type,
price_limit = EXCLUDED.price_limit,
value = EXCLUDED.value,
description = EXCLUDED.description,
enabled = EXCLUDED.enabled,
sort = EXCLUDED.sort,
tenant_id = EXCLUDED.tenant_id,
delete_flag = EXCLUDED.delete_flag;
SELECT setval('jsh_role_id_seq', COALESCE((SELECT MAX(id) FROM jsh_role), 1));

-- ============================================================
-- 23. jsh_sequence - 单据编号表
-- ============================================================
DROP TABLE IF EXISTS jsh_sequence CASCADE;
CREATE TABLE jsh_sequence (
    seq_name VARCHAR(50) NOT NULL PRIMARY KEY,
    min_value BIGINT NOT NULL,
    max_value BIGINT NOT NULL,
    current_val BIGINT NOT NULL,
    increment_val INT NOT NULL DEFAULT 1,
    remark VARCHAR(500)
);
COMMENT ON TABLE jsh_sequence IS '单据编号表';
COMMENT ON COLUMN jsh_sequence.seq_name IS '序列名称';
COMMENT ON COLUMN jsh_sequence.min_value IS '最小值';
COMMENT ON COLUMN jsh_sequence.max_value IS '最大值';
COMMENT ON COLUMN jsh_sequence.current_val IS '当前值';
COMMENT ON COLUMN jsh_sequence.increment_val IS '增长步数';
COMMENT ON COLUMN jsh_sequence.remark IS '备注';

-- 所有业务单据共用的全局编号序列，缺少该记录时新增单据无法自动生成编号
INSERT INTO jsh_sequence
    (seq_name, min_value, max_value, current_val, increment_val, remark)
VALUES
    ('depot_number_seq', 1, 999999999999999999, 0, 1, '单据编号sequence');


-- ============================================================
-- 24. jsh_serial_number - 序列号表
-- ============================================================
DROP TABLE IF EXISTS jsh_serial_number CASCADE;
CREATE TABLE jsh_serial_number (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT,
    depot_id BIGINT,
    serial_number VARCHAR(64),
    is_sell VARCHAR(1) DEFAULT '0',
    in_price DECIMAL(24,6),
    remark VARCHAR(1024),
    create_time TIMESTAMP,
    creator BIGINT,
    update_time TIMESTAMP,
    updater BIGINT,
    in_bill_no VARCHAR(50),
    out_bill_no VARCHAR(50),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_serial_number_material_id ON jsh_serial_number(material_id);
CREATE INDEX idx_serial_number_depot_id ON jsh_serial_number(depot_id);
CREATE INDEX idx_serial_number_tenant_id ON jsh_serial_number(tenant_id);
COMMENT ON TABLE jsh_serial_number IS '序列号表';
COMMENT ON COLUMN jsh_serial_number.id IS '主键';
COMMENT ON COLUMN jsh_serial_number.material_id IS '产品表id';
COMMENT ON COLUMN jsh_serial_number.depot_id IS '仓库id';
COMMENT ON COLUMN jsh_serial_number.serial_number IS '序列号';
COMMENT ON COLUMN jsh_serial_number.is_sell IS '是否卖出，0未卖出，1卖出';
COMMENT ON COLUMN jsh_serial_number.in_price IS '入库单价';
COMMENT ON COLUMN jsh_serial_number.remark IS '备注';
COMMENT ON COLUMN jsh_serial_number.create_time IS '创建时间';
COMMENT ON COLUMN jsh_serial_number.creator IS '创建人';
COMMENT ON COLUMN jsh_serial_number.update_time IS '更新时间';
COMMENT ON COLUMN jsh_serial_number.updater IS '更新人';
COMMENT ON COLUMN jsh_serial_number.in_bill_no IS '入库单号';
COMMENT ON COLUMN jsh_serial_number.out_bill_no IS '出库单号';
COMMENT ON COLUMN jsh_serial_number.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_serial_number.delete_flag IS '删除标记，0未删除，1删除';

-- ============================================================
-- 25. jsh_supplier - 供应商/客户信息表
-- ============================================================
DROP TABLE IF EXISTS jsh_supplier CASCADE;
CREATE TABLE jsh_supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier VARCHAR(255) NOT NULL,
    contacts VARCHAR(100),
    phone_num VARCHAR(30),
    email VARCHAR(50),
    description VARCHAR(500),
    isystem SMALLINT,
    type VARCHAR(20),
    enabled BOOLEAN,
    advance_in DECIMAL(24,6) DEFAULT 0.000000,
    begin_need_get DECIMAL(24,6),
    begin_need_pay DECIMAL(24,6),
    all_need_get DECIMAL(24,6),
    all_need_pay DECIMAL(24,6),
    fax VARCHAR(30),
    telephone VARCHAR(30),
    address VARCHAR(100),
    tax_num VARCHAR(50),
    bank_name VARCHAR(50),
    account_number VARCHAR(50),
    tax_rate DECIMAL(24,6),
    sort VARCHAR(10),
    creator BIGINT,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_supplier_type ON jsh_supplier(type);
CREATE INDEX idx_supplier_tenant_id ON jsh_supplier(tenant_id);
COMMENT ON TABLE jsh_supplier IS '供应商/客户信息表';
COMMENT ON COLUMN jsh_supplier.id IS '主键';
COMMENT ON COLUMN jsh_supplier.supplier IS '供应商名称';
COMMENT ON COLUMN jsh_supplier.contacts IS '联系人';
COMMENT ON COLUMN jsh_supplier.phone_num IS '联系电话';
COMMENT ON COLUMN jsh_supplier.email IS '电子邮箱';
COMMENT ON COLUMN jsh_supplier.description IS '备注';
COMMENT ON COLUMN jsh_supplier.isystem IS '是否系统自带 0==系统 1==非系统';
COMMENT ON COLUMN jsh_supplier.type IS '类型';
COMMENT ON COLUMN jsh_supplier.enabled IS '启用';
COMMENT ON COLUMN jsh_supplier.advance_in IS '预收款';
COMMENT ON COLUMN jsh_supplier.begin_need_get IS '期初应收';
COMMENT ON COLUMN jsh_supplier.begin_need_pay IS '期初应付';
COMMENT ON COLUMN jsh_supplier.all_need_get IS '累计应收';
COMMENT ON COLUMN jsh_supplier.all_need_pay IS '累计应付';
COMMENT ON COLUMN jsh_supplier.fax IS '传真';
COMMENT ON COLUMN jsh_supplier.telephone IS '手机';
COMMENT ON COLUMN jsh_supplier.address IS '地址';
COMMENT ON COLUMN jsh_supplier.tax_num IS '纳税人识别号';
COMMENT ON COLUMN jsh_supplier.bank_name IS '开户行';
COMMENT ON COLUMN jsh_supplier.account_number IS '账号';
COMMENT ON COLUMN jsh_supplier.tax_rate IS '税率';
COMMENT ON COLUMN jsh_supplier.sort IS '排序';
COMMENT ON COLUMN jsh_supplier.creator IS '操作员';
COMMENT ON COLUMN jsh_supplier.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_supplier.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_supplier_id_seq', 1);

-- ============================================================
-- 26. jsh_sys_dict_data - 字典数据表
-- ============================================================
DROP TABLE IF EXISTS jsh_sys_dict_data CASCADE;
CREATE TABLE jsh_sys_dict_data (
    dict_code BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_sort INT DEFAULT 0,
    dict_label VARCHAR(100) DEFAULT '',
    dict_value VARCHAR(100) DEFAULT '',
    dict_type VARCHAR(100) DEFAULT '',
    css_class VARCHAR(100),
    list_class VARCHAR(100),
    is_default CHAR(1) DEFAULT 'N',
    status CHAR(1) DEFAULT '0',
    create_by VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP,
    update_by VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP,
    remark VARCHAR(500),
    delete_flag VARCHAR(1) DEFAULT '0'
);
COMMENT ON TABLE jsh_sys_dict_data IS '字典数据表';
COMMENT ON COLUMN jsh_sys_dict_data.dict_code IS '字典编码';
COMMENT ON COLUMN jsh_sys_dict_data.dict_sort IS '字典排序';
COMMENT ON COLUMN jsh_sys_dict_data.dict_label IS '字典标签';
COMMENT ON COLUMN jsh_sys_dict_data.dict_value IS '字典键值';
COMMENT ON COLUMN jsh_sys_dict_data.dict_type IS '字典类型';
COMMENT ON COLUMN jsh_sys_dict_data.css_class IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN jsh_sys_dict_data.list_class IS '表格回显样式';
COMMENT ON COLUMN jsh_sys_dict_data.is_default IS '是否默认（Y是 N否）';
COMMENT ON COLUMN jsh_sys_dict_data.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN jsh_sys_dict_data.create_by IS '创建者';
COMMENT ON COLUMN jsh_sys_dict_data.create_time IS '创建时间';
COMMENT ON COLUMN jsh_sys_dict_data.update_by IS '更新者';
COMMENT ON COLUMN jsh_sys_dict_data.update_time IS '更新时间';
COMMENT ON COLUMN jsh_sys_dict_data.remark IS '备注';
COMMENT ON COLUMN jsh_sys_dict_data.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_sys_dict_data_dict_code_seq', 1);

-- ============================================================
-- 27. jsh_sys_dict_type - 字典类型表
-- ============================================================
DROP TABLE IF EXISTS jsh_sys_dict_type CASCADE;
CREATE TABLE jsh_sys_dict_type (
    dict_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_name VARCHAR(100) DEFAULT '',
    dict_type VARCHAR(100) DEFAULT '',
    status CHAR(1) DEFAULT '0',
    create_by VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP,
    update_by VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP,
    remark VARCHAR(500),
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE UNIQUE INDEX idx_dict_type_dict_type ON jsh_sys_dict_type(dict_type);
COMMENT ON TABLE jsh_sys_dict_type IS '字典类型表';
COMMENT ON COLUMN jsh_sys_dict_type.dict_id IS '字典主键';
COMMENT ON COLUMN jsh_sys_dict_type.dict_name IS '字典名称';
COMMENT ON COLUMN jsh_sys_dict_type.dict_type IS '字典类型';
COMMENT ON COLUMN jsh_sys_dict_type.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN jsh_sys_dict_type.create_by IS '创建者';
COMMENT ON COLUMN jsh_sys_dict_type.create_time IS '创建时间';
COMMENT ON COLUMN jsh_sys_dict_type.update_by IS '更新者';
COMMENT ON COLUMN jsh_sys_dict_type.update_time IS '更新时间';
COMMENT ON COLUMN jsh_sys_dict_type.remark IS '备注';
COMMENT ON COLUMN jsh_sys_dict_type.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_sys_dict_type_dict_id_seq', 1);

-- ============================================================
-- 28. jsh_system_config - 系统参数
-- ============================================================
DROP TABLE IF EXISTS jsh_system_config CASCADE;
CREATE TABLE jsh_system_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(50),
    company_contacts VARCHAR(20),
    company_address VARCHAR(50),
    company_tel VARCHAR(20),
    company_fax VARCHAR(20),
    company_post_code VARCHAR(20),
    sale_agreement VARCHAR(500),
    depot_flag VARCHAR(1) DEFAULT '0',
    customer_flag VARCHAR(1) DEFAULT '0',
    minus_stock_flag VARCHAR(1) DEFAULT '0',
    purchase_by_sale_flag VARCHAR(1) DEFAULT '0',
    multi_level_approval_flag VARCHAR(1) DEFAULT '0',
    multi_bill_type VARCHAR(200),
    force_approval_flag VARCHAR(1) DEFAULT '0',
    update_unit_price_flag VARCHAR(1) DEFAULT '1',
    over_link_bill_flag VARCHAR(1) DEFAULT '0',
    in_out_manage_flag VARCHAR(1) DEFAULT '0',
    multi_account_flag VARCHAR(1) DEFAULT '0',
    move_avg_price_flag VARCHAR(1) DEFAULT '0',
    audit_print_flag VARCHAR(1) DEFAULT '0',
    zero_change_amount_flag VARCHAR(1) DEFAULT '0',
    customer_static_price_flag VARCHAR(1) DEFAULT '0',
    material_price_tax_flag VARCHAR(1) DEFAULT '0',
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
COMMENT ON TABLE jsh_system_config IS '系统参数';
COMMENT ON COLUMN jsh_system_config.id IS '主键';
COMMENT ON COLUMN jsh_system_config.company_name IS '公司名称';
COMMENT ON COLUMN jsh_system_config.company_contacts IS '公司联系人';
COMMENT ON COLUMN jsh_system_config.company_address IS '公司地址';
COMMENT ON COLUMN jsh_system_config.company_tel IS '公司电话';
COMMENT ON COLUMN jsh_system_config.company_fax IS '公司传真';
COMMENT ON COLUMN jsh_system_config.company_post_code IS '公司邮编';
COMMENT ON COLUMN jsh_system_config.sale_agreement IS '销售协议';
COMMENT ON COLUMN jsh_system_config.depot_flag IS '仓库启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.customer_flag IS '客户启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.minus_stock_flag IS '负库存启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.purchase_by_sale_flag IS '以销定购启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.multi_level_approval_flag IS '多级审核启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.multi_bill_type IS '流程类型，可多选';
COMMENT ON COLUMN jsh_system_config.force_approval_flag IS '强审核启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.update_unit_price_flag IS '更新单价启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.over_link_bill_flag IS '超出关联单据启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.in_out_manage_flag IS '出入库管理启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.multi_account_flag IS '多账户启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.move_avg_price_flag IS '移动平均价启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.audit_print_flag IS '先审核后打印启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.zero_change_amount_flag IS '零收付款启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.customer_static_price_flag IS '客户静态单价启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.material_price_tax_flag IS '商品价格含税启用标记，0未启用，1启用';
COMMENT ON COLUMN jsh_system_config.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_system_config.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_system_config_id_seq', 1);

-- ============================================================
-- 29. jsh_tenant - 租户
-- ============================================================
DROP TABLE IF EXISTS jsh_tenant CASCADE;
CREATE TABLE jsh_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    login_name VARCHAR(255),
    user_num_limit INT,
    type VARCHAR(1) DEFAULT '0',
    enabled BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP,
    expire_time TIMESTAMP,
    remark VARCHAR(500),
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_tenant_create_time ON jsh_tenant(create_time);
CREATE INDEX idx_tenant_tenant_id ON jsh_tenant(tenant_id);
COMMENT ON TABLE jsh_tenant IS '租户';
COMMENT ON COLUMN jsh_tenant.id IS '主键';
COMMENT ON COLUMN jsh_tenant.tenant_id IS '用户id';
COMMENT ON COLUMN jsh_tenant.login_name IS '登录名';
COMMENT ON COLUMN jsh_tenant.user_num_limit IS '用户数量限制';
COMMENT ON COLUMN jsh_tenant.type IS '租户类型，0免费租户，1付费租户';
COMMENT ON COLUMN jsh_tenant.enabled IS '启用 0-禁用  1-启用';
COMMENT ON COLUMN jsh_tenant.create_time IS '创建时间';
COMMENT ON COLUMN jsh_tenant.expire_time IS '到期时间';
COMMENT ON COLUMN jsh_tenant.remark IS '备注';
COMMENT ON COLUMN jsh_tenant.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_tenant_id_seq', 1);

-- ============================================================
-- 30. jsh_unit - 多单位表
-- ============================================================
DROP TABLE IF EXISTS jsh_unit CASCADE;
CREATE TABLE jsh_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    basic_unit VARCHAR(50),
    other_unit VARCHAR(50),
    other_unit_two VARCHAR(50),
    other_unit_three VARCHAR(50),
    ratio DECIMAL(24,3),
    ratio_two DECIMAL(24,3),
    ratio_three DECIMAL(24,3),
    enabled BOOLEAN,
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
COMMENT ON TABLE jsh_unit IS '多单位表';
COMMENT ON COLUMN jsh_unit.id IS '主键';
COMMENT ON COLUMN jsh_unit.name IS '名称，支持多单位';
COMMENT ON COLUMN jsh_unit.basic_unit IS '基础单位';
COMMENT ON COLUMN jsh_unit.other_unit IS '副单位';
COMMENT ON COLUMN jsh_unit.other_unit_two IS '副单位2';
COMMENT ON COLUMN jsh_unit.other_unit_three IS '副单位3';
COMMENT ON COLUMN jsh_unit.ratio IS '比例';
COMMENT ON COLUMN jsh_unit.ratio_two IS '比例2';
COMMENT ON COLUMN jsh_unit.ratio_three IS '比例3';
COMMENT ON COLUMN jsh_unit.enabled IS '启用';
COMMENT ON COLUMN jsh_unit.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_unit.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_unit_id_seq', 1);

-- ============================================================
-- 31. jsh_user - 用户表
-- ============================================================
DROP TABLE IF EXISTS jsh_user CASCADE;
CREATE TABLE jsh_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    login_name VARCHAR(255) NOT NULL,
    password VARCHAR(50),
    leader_flag VARCHAR(1) DEFAULT '0',
    position VARCHAR(200),
    department VARCHAR(255),
    email VARCHAR(100),
    phonenum VARCHAR(100),
    ismanager SMALLINT NOT NULL DEFAULT 1,
    isystem SMALLINT NOT NULL DEFAULT 0,
    status SMALLINT DEFAULT 0,
    description VARCHAR(500),
    remark VARCHAR(500),
    weixin_open_id VARCHAR(100),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
COMMENT ON TABLE jsh_user IS '用户表';
COMMENT ON COLUMN jsh_user.id IS '主键';
COMMENT ON COLUMN jsh_user.username IS '用户姓名--例如张三';
COMMENT ON COLUMN jsh_user.login_name IS '登录用户名';
COMMENT ON COLUMN jsh_user.password IS '登陆密码';
COMMENT ON COLUMN jsh_user.leader_flag IS '是否经理，0否，1是';
COMMENT ON COLUMN jsh_user.position IS '职位';
COMMENT ON COLUMN jsh_user.department IS '所属部门';
COMMENT ON COLUMN jsh_user.email IS '电子邮箱';
COMMENT ON COLUMN jsh_user.phonenum IS '手机号码';
COMMENT ON COLUMN jsh_user.ismanager IS '是否为管理者 0==管理者 1==员工';
COMMENT ON COLUMN jsh_user.isystem IS '是否系统自带数据';
COMMENT ON COLUMN jsh_user.status IS '状态，0正常，2封禁';
COMMENT ON COLUMN jsh_user.description IS '用户描述信息';
COMMENT ON COLUMN jsh_user.remark IS '备注';
COMMENT ON COLUMN jsh_user.weixin_open_id IS '微信绑定';
COMMENT ON COLUMN jsh_user.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_user.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_user_id_seq', 1);

INSERT INTO jsh_user (id, username, login_name, password, leader_flag, position, department, email, phonenum, ismanager, isystem, status, description, remark, weixin_open_id, tenant_id, delete_flag) VALUES
(120, '管理员', 'admin', 'e10adc3949ba59abbe56e057f20f883e', '0', NULL, NULL, NULL, NULL, 1, 0, 0, '平台运维管理员', NULL, NULL, 0, '0')
ON CONFLICT (id) DO UPDATE SET
username = EXCLUDED.username,
login_name = EXCLUDED.login_name,
password = EXCLUDED.password,
leader_flag = EXCLUDED.leader_flag,
position = EXCLUDED.position,
department = EXCLUDED.department,
email = EXCLUDED.email,
phonenum = EXCLUDED.phonenum,
ismanager = EXCLUDED.ismanager,
isystem = EXCLUDED.isystem,
status = EXCLUDED.status,
description = EXCLUDED.description,
remark = EXCLUDED.remark,
weixin_open_id = EXCLUDED.weixin_open_id,
tenant_id = EXCLUDED.tenant_id,
delete_flag = EXCLUDED.delete_flag;
SELECT setval('jsh_user_id_seq', COALESCE((SELECT MAX(id) FROM jsh_user), 1));

-- ============================================================
-- 32. jsh_user_business - 用户/角色/模块关系表
-- ============================================================
DROP TABLE IF EXISTS jsh_user_business CASCADE;
CREATE TABLE jsh_user_business (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),
    key_id VARCHAR(50),
    value TEXT,
    btn_str VARCHAR(20000),
    tenant_id BIGINT,
    delete_flag VARCHAR(1) DEFAULT '0'
);
CREATE INDEX idx_user_business_type ON jsh_user_business(type);
CREATE INDEX idx_user_business_key_id ON jsh_user_business(key_id);
CREATE INDEX idx_user_business_tenant_id ON jsh_user_business(tenant_id);
COMMENT ON TABLE jsh_user_business IS '用户/角色/模块关系表';
COMMENT ON COLUMN jsh_user_business.id IS '主键';
COMMENT ON COLUMN jsh_user_business.type IS '类别';
COMMENT ON COLUMN jsh_user_business.key_id IS '主id';
COMMENT ON COLUMN jsh_user_business.value IS '值';
COMMENT ON COLUMN jsh_user_business.btn_str IS '按钮权限';
COMMENT ON COLUMN jsh_user_business.tenant_id IS '租户id';
COMMENT ON COLUMN jsh_user_business.delete_flag IS '删除标记，0未删除，1删除';

SELECT setval('jsh_user_business_id_seq', 1);

INSERT INTO jsh_user_business (id, type, key_id, value, btn_str, tenant_id, delete_flag) VALUES
(111, 'UserRole', '120', '[4]', NULL, 0, '0'),
(112, 'RoleFunctions', '4', '[1][13][14][15][16][18][21][22][23][24][25][26][31][32][33][38][40][41][44][59][194][195][197][198][199][200][201][202][203][204][205][206][207][208][209][210][211][212][217][218][220][225][226][227][228][229][232][233][234][235][236][237][239][241][242][243][244][245][246][247][248][258][259][260][261]', '[{"funId":13,"btnStr":"1"},{"funId":14,"btnStr":"1"},{"funId":243,"btnStr":"1"},{"funId":234,"btnStr":"1"},{"funId":236,"btnStr":"1"},{"funId":16,"btnStr":"1"},{"funId":18,"btnStr":"1"},{"funId":258,"btnStr":"1"},{"funId":22,"btnStr":"1"},{"funId":23,"btnStr":"1,3"},{"funId":220,"btnStr":"1"},{"funId":247,"btnStr":"1"},{"funId":25,"btnStr":"1,3"},{"funId":217,"btnStr":"1,3"},{"funId":218,"btnStr":"1,3"},{"funId":26,"btnStr":"1"},{"funId":194,"btnStr":"1"},{"funId":195,"btnStr":"1"},{"funId":31,"btnStr":"1"},{"funId":261,"btnStr":"1,2,7,3"},{"funId":241,"btnStr":"1,2,7,3"},{"funId":33,"btnStr":"1,2,7,3"},{"funId":199,"btnStr":"1,2,7,3"},{"funId":242,"btnStr":"1,2,7,3"},{"funId":41,"btnStr":"1,2,7,3"},{"funId":200,"btnStr":"1,2,7,3"},{"funId":210,"btnStr":"1,2,7,3"},{"funId":211,"btnStr":"1,2,7,3"},{"funId":197,"btnStr":"1,7,2,3"},{"funId":203,"btnStr":"1,7,2,3"},{"funId":204,"btnStr":"1,7,2,3"},{"funId":205,"btnStr":"1,2,7,3"},{"funId":206,"btnStr":"1,2,7,3"},{"funId":212,"btnStr":"1,7,2,3"},{"funId":201,"btnStr":"1,2,7,3"},{"funId":202,"btnStr":"1,2,7,3"},{"funId":40,"btnStr":"1,2,7,3"},{"funId":232,"btnStr":"1,2,7,3"},{"funId":233,"btnStr":"1,2,7,3"}]', 0, '0')
ON CONFLICT (id) DO UPDATE SET
type = EXCLUDED.type,
key_id = EXCLUDED.key_id,
value = EXCLUDED.value,
btn_str = EXCLUDED.btn_str,
tenant_id = EXCLUDED.tenant_id,
delete_flag = EXCLUDED.delete_flag;
SELECT setval('jsh_user_business_id_seq', COALESCE((SELECT MAX(id) FROM jsh_user_business), 1));
SELECT setval('jsh_depot_head_id_seq', 1);
SELECT setval('jsh_depot_item_id_seq', 1);
SELECT setval('jsh_account_head_id_seq', 1);
SELECT setval('jsh_account_item_id_seq', 1);
SELECT setval('jsh_material_initial_stock_id_seq', 1);

-- ============================================================
-- 完成：更新统计信息
-- ============================================================
ANALYZE;
