CREATE TABLE IF NOT EXISTS jsh_stock_warning_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    depot_id BIGINT NOT NULL,
    warning_type VARCHAR(10) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    current_stock DECIMAL(20,8),
    notify_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_stock_warning_status
        UNIQUE (tenant_id, material_id, depot_id, warning_type),
    CONSTRAINT ck_stock_warning_type CHECK (warning_type IN ('LOW', 'HIGH'))
);

CREATE INDEX IF NOT EXISTS idx_sws_tenant_active
    ON jsh_stock_warning_status(tenant_id, active);

COMMENT ON TABLE jsh_stock_warning_status IS 'Stock warning transition state';
COMMENT ON COLUMN jsh_stock_warning_status.warning_type IS 'LOW or HIGH';
COMMENT ON COLUMN jsh_stock_warning_status.active IS 'Whether the warning is currently active';
